### ISSUE TITLE
„Alt Alt Alt“ in the Gamelist

### ISSUE THREAD

**Issue by Kickstart2000** [MrZammler/iGame#154] opened 2021-08-05 16:45 UTC
Hello,
I have the following problem with Igame:
I have a new folder with Whdload Games. When I scan this, the games are listed in Igame but also very, very many lines with:
alt
alt alt
alt alt alt...

I have already deleted them in gameslist .csv but they keep appearing.
Any idea?

**Comment by walkero-gr** [comment] 2021-08-05 17:40
@Kickstart2000 Thank you for the message. Try to select from preferences to use the folder name for the games and rescan the repositories. Possible you are going to get a better result.

**Comment by walkero-gr** [comment] 2021-09-28 12:03
@Kickstart2000 Was that solved base on my previous suggestion?

**Comment by DisasterIncarnate** [comment] 2021-10-02 06:51
the problem is when igame detects an "alt" game, it remembers that this is "alt number x/y/z" for everything and not just and alt for that 1 particular game, so if you get 3 alts for say cannon fodder and it moves on to chaos engine and finds 2 alts for chaos engine it shows like this.

Cannon Fodder
Cannon Fodder Alt
Cannon Fodder Alt Alt
Cannon Fodder Alt Alt Alt
Chaos Engine
Chaos Engine Alt Alt Alt Alt
Chaos Engine Alt Alt Alt Alt Alt

The alts become globally accumulative rather than resetting on the next detected game until you end up with titles with far too many Alts in them and igame crashes or just spams alt on a load of titles.

**Comment by walkero-gr** [comment] 2021-11-25 00:03
@DisasterIncarnate Hello there. I am looking at the problem you mention above, so to fix it and I can't reproduce it at all. Which version of iGame are you using?

**Comment by DisasterIncarnate** [comment] 2022-02-06 21:51
i'm using v2.0 (2020-10-16) this has happened on many versions however.

For example to get a load of alt's all ive had to do is say add a load of "similar" games, such as say the multitude of lemmings games/versions, they often get identified as the same game and a load of alts appear.

Then igame having added the correct Lemmings and a load of alts will move on to the next game, lets say that game also has a multitude of various versions such as the alien breed games, again several get identified correctly but a load of alts will show up, but those alts will accumulate on top of the previous alts.

then the config ends up having far far too many alt entries and igame crashes during a scan, likely because the config has been spammed with alt entries.

I had the same issue when setting up a second igame in a different location just for Demos/Megademos, the config went batshit crazy with all the various demos that contained the word "MegaDemo", the number of alt entries was..... numerous and all needed manually removed.

**Comment by walkero-gr** [comment] 2022-02-07 00:14
@DisasterIncarnate Have you tried to set in preferences for iGame to get the game name from the folder and not from the slave file? Does this solve the issues you mention above?

**Comment by DisasterIncarnate** [comment] 2022-02-19 11:43
it fixes a lot of the problems but not all of them.

**Comment by DisasterIncarnate** [comment] 2022-11-19 18:31
quick note here, on my own game/startup-sequence selector tool, i am handling "alt" entries by waiting until a full scan is done and my list performs a sort to correctly have everything listed, then i rescan the list and i have each entry check the previous 10-20 entries for a matching name and if the previous entry matches the current one, rather than add "Alt" i add an identifier showing its a duplicate/same names Slave file and i append a number, this means newer "alt2 entries can confirm a previous match and can confirm via the added "Slave: <Number>" that yet another matching entry should name itsself the same with 1 number higher than the previous.

Example Here: https://i.imgur.com/biasryN.jpg

Currently cant think of a better way to handle duplicates and this is "sort of" working for me atm, tho when i resort the completed list its annoying that my 1st entry gets added to the bottom of the duplicates not the top :D

**Comment by walkero-gr** [comment] 2023-04-16 21:24
@Kickstart2000 @DisasterIncarnate 
A few days ago I released a new version of iGame. Can you please check this one with your setup and let me know how it works? I would suggest though to do a new installation and rescan your collection

**Comment by walkero-gr** [comment] 2023-04-20 17:38
This should be fixed on [2.3.0](https://github.com/MrZammler/iGame/releases/tag/v2.3.0) and above

**Closed by walkero-gr** 2023-04-20 17:38 UTC
Labels: bug
