### ISSUE TITLE
Catalog not loading for iGame

### ISSUE THREAD

**Issue by coldacid** [MrZammler/iGame#103] opened 2020-09-11 01:21 UTC
There are two related issues preventing iGame from running localized:

1. The file name of the catalog descriptor is used when generating the catalog source files to determine the file name of the catalog file that is actually opened. Since the catalog descriptor is `iGameStrings.cd` the generated `iGameStrings_cat.c` code for opening the catalog looks for `iGameStrings.catalog` rather than `iGame.catalog` as expected.
2. With VBCC and the currently generated code, the catalog file is never actually opened. With GCC (and DICE C) the functions for opening and closing the catalog are set up to be automatically called before and after `main()` using those compilers' features, but while VBCC supports similar functionality the functions aren't set up for that.

**Comment by walkero-gr** [comment] 2020-09-11 08:44
@coldacid Your #104 I guess fixes that. I would say let's push that for v2.1 because we currently do not have any catalogs for other languages. Meanwhile we can request fro contribution from the community.
Do you agree?

**Comment by coldacid** [comment] 2020-09-11 12:53
@walkero-gr yeah, that's fine. However it'll be harder for those translation contributions to come in if people can't test them themselves. There _is_ an Italian translation inside the lha file in contrib/ that I'm looking at tidying up, though, but I don't personally know the language and so for changed/added messages the best I can do is Google Translate. (Fortunately there doesn't seem to be more than a half-dozen such cases.)

As it is, I can't get the catalogs to actually load even with the code template changes for VBCC. While I did PR #104 already, I've put it into draft mode until I can work it out.

**Comment by walkero-gr** [comment] 2020-09-11 14:22
We can provide the translators with beta versions of iGame, so they can test them. Those betas will be released after v2.0 is finalized and released.

**Comment by coldacid** [comment] 2020-09-11 20:03
I've figured out the problem that was still preventing catalogs from loading, and the PR for this is ready.

**Comment by samo79** [comment] 2020-10-16 18:08
I'm the author of the italian translation .. and i can confirm that for now the catalog does not work
if i'm understanding correctly it will just need to be renamed ?
Maybe as "iGameString.catalog" ?

If so i can try and report back

**Comment by coldacid** [comment] 2020-10-19 16:14
@samo79 your catalog file isn't the problem. It's that catalog support was never integrated after the move away from MUI Builder.

**Closed** 2020-10-27 21:06 UTC
Labels: bug
