### ISSUE TITLE
Problems getting it running

### ISSUE THREAD

**Issue by Troelz** [MrZammler/iGame#47] opened 2018-10-22 16:46 UTC
Hi Dimitris.

I tried updating my iGame to latest BETA: iGame-2.0b4

I copied the files from old iGame library to new iGame2 library (except the old iGame program), but when I start it up i get:

1: A popup window "Execute a File", which I have to click OK to
I suppose this is because it's not a finished program and normal?

2: Then another popup window "No settings file found, will attempt to read Tooltypes instead
I suppose this is just because it's the first time i start up the program and normal?

3: If I do nothing, and close the program, I can start it again.
But if I go to settings and change 'Titles' to Directories and the Save - I cannot open the program again.
If I just scan using Slave Contents, there is also no issue.

Tried the other previous beta release as well, same issue.

Old iGame v1.5 works very well.

Using WinUAE to set up.
Installed OS is Classic Workbench Full

***update1
I tried selecting (from a fresh "install") >No GuiGfx< from Settings, then saving and closing the program. This creates the igame.prefs file, and reloading the program launches just fine.

If I then add a repository and close the program, this creates the repos.prefs file, and now program won't load. With or without any game scan done. Deleting this file again, and the program launches again.
If I scan repositories, with >Directories< the gameslist is updated and everything looks fine. But again, program won't launch again.
Tried creating a small games library with only a few games, and using that as a repository, but same as above.

***Update2
Trying again and again and again, now it seems to work... Very strange
I'll do some more testing :)

***Update3
OK, so after adding another game, and starting scan, it came up empty.
I looked at Repositories-settings, and suddenly it was not WHDLoad:Games but WHDLoad:Game
I removed it and added the correct one again, and then it came up with the titles with ALT like before.
And now I'm back to the beginning with it not running after clean install... Sigh...

***Update4
OK, so disabling GuiGfx seems to "fix it".
I tried disabling it, and scanned games folder, which added 2891 games with directory titles.
Tried closing and opening it, works.
Tried adding a non WHDLoad game, and then scanning again.
1 game remained - the non whdload.
Looking at Repositories, it has now changed again to WHDLoad:Game
Tried closing iGame, and opening again - 2892 games, including the non-whdload game.
Now repositories changed to WHDLoad:Gam
Tried closing it and opening again - now repositories changed again, to WHDLoad:Ga
Again closing and reopening, and one more letter gone...
Continued to do this closing and reopening until all the letters were gone, and now they all are, I can't scan the library any more - but the games are still there.
I then added the directory again under repositories, and did a scan - all games now have Alt at the end of the name, even though the settings are still Directories..

Very strange behavior.

I know it's a lot of info, and would love to do a video, or add some screenshots or files if you need them.

**Comment by MrZammler** [comment] 2018-10-25 19:21
Hi Troelz, thanks a lot for your tests.

I will have a look on this, try to reproduce at least some of the issues, and see what we can do.

**Comment by MrZammler** [comment] 2018-11-01 19:29
Since there's no installer to update iGame, at this point the safest way is to open a shell and copy just the binary from the new iGame folder over the old one.

In any case, since these are beta builds, you really should keep the gameslist file somewhere safe...

**Comment by walkero-gr** [comment] 2023-04-20 18:09
@Troelz This should be fixed by now. If not please reopen this ticket

**Closed by walkero-gr** 2023-04-20 18:09 UTC
Labels: investigation
